# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Install node
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
        
    - run: echo ::set-env name=workspace::$GITHUB_WORKSPACE

    - name: Set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

    # Runs a set of commands using the runners shell
    - name: jest
      id: jest
      run: |
        cd src/
        yarn --frozen-lockfile
        yarn test
      # continue-on-error: true
    - name: manifest Version
      if: failure()
      uses: deef0000dragon1/json-edit-action/@v1
      env:
        KEY: version
        VALUE: v0.1.1
        FILE: ${{ env.workspace }}/src/testResults.json
    - name: manifest Version1223
      if: failure()
      uses: deef0000dragon1/json-edit-action/@v1
      env:
        KEY: version1223
        VALUE: ${{ steps.vars.outputs.sha_short }}
        FILE: ${{ env.workspace }}/src/testResults.json
    - name: onFailure
      if: failure()
      id: package
      uses: juliangruber/read-file-action@v1
      with:
        path: ${{ env.workspace }}/src/testResults.json
    - name: Echo package.json
      if: failure()
      run: echo "${{ steps.package.outputs.content }}"
